schema_version = "1.0.0"

id = "KyokazToolbox"
version = "2.6.5"
name = "Kyokaz's Toolbox"
tagline = "Set of useful camera, animation and rendering tools for Blender"
maintainer = "Kyokaz <faizkyokaz@gmail.com>"
type = "add-on"

website = "https://github.com/Kyokaz/Kyokaz-s-Toolbox"

tags = ["Animation", "Camera", "Render", "User Interface"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]